name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v2
      
    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: 🧹 Clean
      run: dotnet clean src/server/FluentPOS.sln -c Release && dotnet nuget locals all --clear

    - name: 🔁 Restore dependencies
      run: dotnet restore
      working-directory: src/server
      
    - name: 🛠️ Build
      run: dotnet build --no-restore
      working-directory: src/server

#   - name: 🧪 Run unit tests
#     run: dotnet test src/server -c Release --no-build
